gpu: "0"
multi_gpu: null

model_name: ContextAwareResFlow

full: False

evaluate: True
resume: True
ckpt_dir: ./pretrain_weights/

# general args
batch_size: 20
pretrain: ContextAwareResFlow_774_0.0357.pth
dim: 3
num_points: 8192

DEVICE: cuda

dataset: FlyingThings3DSubset #KITTI
data_root: ../../dataset

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# miscalleneous
workers: 16

is_training: True








